### ISSUE TITLE
Some compile errors and their solutions

### ISSUE THREAD

**Issue by pmichel31415** [mrzv/dionysus#1]
Hi,

First I must say I was very happy to find out about this subject, I had struggled with using dionysus in python in its previous iteration and it seems to be working like a charm now.

When I tried to compile on my machine I ran into two errors, I'm sharing them here with the solution for your information. If you want I can do a pull request.

- `dionysus/ext/hera/wasserstein/src/basic_defs.cpp:101:74: error: ‘pow’ is not a member of ‘std’`
    - Solution: I added `#include <cmath>` in `basic_defs.cpp`

- An `converting to [...] from initializer list would use explicit constructor [...]` error at `dionysus/bindings/python/zigzag-persistence.cpp:141:58`
    - Solution: change the faulty line to `return std::tuple<PyZigzagPersistence, std::vector<PyDiagram>> { std::move(persistence), std::move(diagrams) };`

Hope that helps, and thanks for developping this library!

**Comment by mrzv** [comment]
That was quick. Thanks for the bug report and for the suggested fixes. I've pushed the correction to both, but since neither one was triggering my compiler, can you please check that the problems are indeed fixed? (I used `make_tuple(...)` for the second one, rather than the explicit constructor call.)

Out of curiosity, what compiler are you using?

I'll pass the first problem and solution upstream, to Hera.

**Comment by pmichel31415** [comment]
It worked, thanks!

I was using gcc 5.4.0

**Comment by mrzv** [comment]
Great! Thanks.
